# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T09:28:04+00:00

from __future__ import annotations

from enum import Enum
from typing import List, Optional

from pydantic import BaseModel, RootModel


class NetworkType(Enum):
    fixed_line = 'fixed_line'
    fixed_line_or_mobile = 'fixed_line_or_mobile'
    mobile = 'mobile'
    pager = 'pager'
    personal_number = 'personal_number'
    premium_rate = 'premium_rate'
    shared_cost = 'shared_cost'
    toll_free = 'toll_free'
    uan = 'uan'
    unknown = 'unknown'
    voicemail = 'voicemail'
    voip = 'voip'


class Carrier(BaseModel):
    country: Optional[str] = None
    name: Optional[str] = None
    network_code: Optional[str] = None
    network_type: Optional[NetworkType] = None


class Mnp(BaseModel):
    country: Optional[str] = None
    international_formatted: Optional[str] = None
    isPorted: Optional[bool] = None
    mccmnc: Optional[str] = None
    national_format: Optional[str] = None
    network: Optional[str] = None
    number: Optional[str] = None


class Status(Enum):
    unknown = 'unknown'
    roaming = 'roaming'
    not_roaming = 'not_roaming'


class Roaming(BaseModel):
    roaming_country_code: Optional[str] = None
    roaming_network_code: Optional[str] = None
    roaming_network_name: Optional[str] = None
    status: Optional[Status] = None


class GroupBy(Enum):
    date = 'date'
    label = 'label'
    subaccount = 'subaccount'
    country = 'country'


class AnalyticsGetResponse(BaseModel):
    date: Optional[str] = None
    direct: Optional[int] = None
    economy: Optional[int] = None
    hlr: Optional[int] = None
    inbound: Optional[int] = None
    mnp: Optional[int] = None
    usage_eur: Optional[float] = None
    voice: Optional[int] = None


class Action(Enum):
    read = 'read'


class Json(Enum):
    number_0 = 0
    number_1 = 1


class Action2(Enum):
    del_ = 'del'
    write = 'write'


class Action4(Enum):
    read = 'read'


class Hook(BaseModel):
    created: Optional[str] = None
    event_type: Optional[str] = None
    id: Optional[str] = None
    request_method: Optional[str] = None
    target_url: Optional[str] = None


class HooksGetResponse(BaseModel):
    hooks: Optional[List[Hook]] = None
    success: Optional[bool] = None


class Action6(Enum):
    subscribe = 'subscribe'
    unsubscribe = 'unsubscribe'


class EventType(Enum):
    all = 'all'
    sms_mo = 'sms_mo'
    dlr = 'dlr'
    voice_status = 'voice_status'


class RequestMethod(Enum):
    POST = 'POST'
    JSON = 'JSON'
    GET = 'GET'


class HooksPostResponse(BaseModel):
    id: Optional[int] = None
    success: Optional[bool] = None


class Number(RootModel[List[str]]):
    root: List[str]


class Debug(Enum):
    number_1 = 1
    number_0 = 0


class NoReload(Enum):
    number_1 = 1
    number_0 = 0


class Unicode(Enum):
    number_1 = 1
    number_0 = 0


class Flash(Enum):
    number_1 = 1
    number_0 = 0


class Utf8(Enum):
    number_1 = 1
    number_0 = 0


class Details(Enum):
    number_1 = 1
    number_0 = 0


class ReturnMsgId(Enum):
    number_1 = 1
    number_0 = 0


class Json4(Enum):
    number_1 = 1
    number_0 = 0


class PerformanceTracking(Enum):
    number_1 = 1
    number_0 = 0


class Message(BaseModel):
    encoding: Optional[str] = None
    error: Optional[str] = None
    error_text: Optional[str] = None
    id: Optional[str] = None
    messages: Optional[List[str]] = None
    parts: Optional[int] = None
    price: Optional[int] = None
    recipient: Optional[str] = None
    sender: Optional[str] = None
    success: Optional[bool] = None
    text: Optional[str] = None


class SmsType(Enum):
    economy = 'economy'
    direct = 'direct'


class SmsPostResponse(BaseModel):
    balance: Optional[float] = None
    debug: Optional[str] = None
    messages: Optional[List[Message]] = None
    sms_type: Optional[SmsType] = None
    success: Optional[str] = None
    total_price: Optional[float] = None


class SmsPostResponse1(BaseModel):
    balance: Optional[float] = None
    debug: Optional[str] = None
    messages: Optional[List[Message]] = None
    sms_type: Optional[SmsType] = None
    success: Optional[str] = None
    total_price: Optional[float] = None


class ValidateForVoicePostResponse(BaseModel):
    code: Optional[str] = None
    error: Optional[str] = None
    success: Optional[bool] = None


class Xml(Enum):
    number_1 = 1
    number_0 = 0
